### ISSUE TITLE
Rework condition for JSON-B recipe

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#328]
The condition needs to check if Spring Boot version is `2.7` and if any JSON-B dependency exists.

**Comment by sanagaraj-pivotal** [comment]
I think we do not need this feature because this file: [boot-2.7-3.0-dependency-version-update.yaml](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/boot-2.7-3.0-dependency-version-update.yaml) has already a root level condition to make sure the spring boot project is 2.7.+ and hence we do not need a separate condition for JSON-B recipe

**Comment by fabapp2** [comment]
righty, works for me. Closing the issue now.
