### ISSUE TITLE
Apply `initialize-spring-boot-migration` on a Boot application might downgrade Boot version

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#453]
**Describe the bug**
Scanning the (see zip) Spring Boot application and applying `initialize-spring-boot-migration` downgrades the Spring Boot version from `2.7.4` to `2.7.3`

**To Reproduce**
see above

**Expected behavior**
The version should be untouched if it is same or more recent than the declared version.

**Comment by sanagaraj-pivotal** [comment]
In the above project the condition to check if a project is a Spring app is by checking if the app uses SpringBootApplication Annotation in the project since the above project does not import appropriate jar SpringBootApplication Annotation was not resolved and  hence SBM inferred that the project is not a spring project.

**Comment by fabapp2** [comment]
Hi @sanagaraj-pivotal 
But the recipe (some action) downgrades the dependency, this should not happen imho.
