### ISSUE TITLE
Not able to get the org.springframework.sbm eclipse plugin

### ISSUE THREAD

**Issue by bsmahi** [spring-projects-experimental/spring-boot-migrator#712]
Firstly, many thanks for spring-boot migrator

Am trying to integrate the spring boot migrator in either IntelliJ and STS from the steps provided in ide-integrations/eclipse/com.vmware.bootifier and trying to expose SBM as a REST service.

However, being unable to find the 'org.springframework.sbm' eclipse plugin, could you please help me.

Your help is greatly appreciated.

Thanks,
Mahi

**Comment by fabapp2** [comment]
Hi @bsmahi,
thanks for trying SBM.

Looking at the README I think `com.vmware.bootifier` needs to be renamed to `com.vmware.sbm` and then it's the plugin mentioned to be under `<SBM Root Folder>/ide-integrations/eclipse/org.springframework.sbm`. The REST Service was changed too. Nevertheless, I think you could get this working again...

 Besides these there were other efforts targeting IDE integration:
- There's a spike for WebSocket communication so that the backend can publish messages to the client.
- @BoykoAlex is actively working on an OpenRewrite integration behind a Spring Language Server for STS where I could see SBM fit into one day.

If you’re serious about looking into an IDE integration for SBM we’d be glad to take contributions. 
I’d see the WebSocket integration as a natural first step as WebSocket can also be used with LS protocol. 
The important advantage over REST is the ability for simple notifications sent from the backend to the client which is important for things such as status updates for long-running recipes or recipes that require user input.

Feel free to reopen the issue in case you need further assistance or want to discuss IDE integration.

**Comment by bsmahi** [comment]
Hi @fabapp2,

Sure thanks for your reply :). I will explore further.

Sure, am happy to contribute in IDE integration and will work with @BoykoAlex. 

By the way, have given one Pull Request for code improvement have done for Spring Spell module (https://github.com/spring-projects-experimental/spring-boot-migrator/pull/713)

@BoykoAlex could you please let me know how to pick up this task, am happy to connect with you as well.

Thanks,
Mahi
