### ISSUE TITLE
Remove dependency to Junit4 

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#775]
### What needs to be done
Remove JUnit4 from classpath

### Why it needs to be done
Some dependency pulls in JUnit 4.
We use JUnit 5 and having both in the classpath could lead to wrong annotations being used, e.g. `@Test`.

### Acceptance Criteria
a `mvn dependency:tree` should not contain any `junit:junit:4.x` dependency

**Comment by Rayan1605** [comment]
I can do this if you wish

**Comment by nikhilyedke1995** [comment]
Hi, Can I work on this? I'm a first time contributor.

**Comment by szymonsadowski3** [comment]
This may not be straightforward to achieve, since the junit4 comes from testcontainers, where it has been an issue for a long time:

![obraz](https://user-images.githubusercontent.com/18751715/234784187-72c42189-878c-4ea2-ac90-054d7d04f586.png)

See relevant issue in testcontainers project: https://github.com/testcontainers/testcontainers-java/issues/970. There are some workarounds mentioned though, may be worth to try them out

**Comment by fabapp2** [comment]
Hello everyone!
first of all, I am happy and grateful for the great interest to contribute and your fast replies to this issue 🤩 

@szymonsadowski3 thanks for pointing this out. It seems indeed harder than I thought.
I was hoping JUnit 4 slipped in recently somehow (we had pain after accidentally using wrong `@Test` annotation yesterday).

It seems not to be as straightforward as just excluding a transitive dependency. 
@Rayan1605 you asked first if you want to pick this and see if you can get it done - more than happy.
If not @nikhilyedke1995 can give it a try, otherwise we live with JUnit 4 for now, I guess...

I plan to clean up the backlog soon and create/find new issues that are (hopefully) a good start.
@nikhilyedke1995 keep an eye on it, please.

**Comment by fabapp2** [comment]
You've been fast @szymonsadowski3 🏎️ 
Nice idea of using the enforce plugin. @Rayan1605 ?

fixed with #777
